M48
; DRILL file {KiCad 9.0.7} date 2026-09-30T15:59:44+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-30T15:59:44+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.600
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C4.500
%
G90
G05
T1
X248.95Y-66.02
T2
X52.0Y-114.0
X52.0Y-341.0
X244.0Y-82.0
X244.0Y-341.0
T3
X61.0Y-59.66
X61.0Y-101.66
X103.0Y-59.66
X103.0Y-101.66
M30
